apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
type: Opaque
data:
  POSTGRES_USERNAME: {{ .Values.global.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.password | b64enc }}
  ELASTICSEARCH_USERNAME: {{ .Values.logsight.elasticsearch.username | b64enc }}
  ELASTICSEARCH_PASSWORD: {{ .Values.logsight.elasticsearch.password | b64enc }} 
  