
apiVersion: v2
name: logsight
description: Logsight infuses deep learning and AI-powered analytics to enable continuous software delivery and proactive troubleshooting.
type: application

version: 0.1.2
appVersion: v1.3.1-pre
keywords:
  - logs
  - analytics

home: https://logsight.ai
icon: https://logsight.ai/assets/img/logo-logsight.svg

maintainers:
  - name: petar-ilijevski-logsight
    email: petar.ilijevski@logsight.ai

dependencies:
- name: kafka
  version: 16.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled
- name: postgresql
  version: 11.1.12
  repository: https://charts.bitnami.com/bitnami
- name: elasticsearch
  version: 7.16.2
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: kibana
  version: 7.16.2
  repository: https://helm.elastic.co
- name: logsight-backend
  version: 0.1.2
  repository: file://./charts/logsight-backend
- name: logsight-pipeline
  version: 0.1.2
  repository: file://./charts/logsight-pipeline
- name: logsight-frontend
  version: 0.1.2
  repository: file://./charts/logsight-frontend
- name: logsight-result-api
  version: 0.1.2
  repository: file://./charts/logsight-result-api
- name: logsight-jobs
  version: 0.1.2
  repository: file://./charts/logsight-jobs