logsight:

  logsight_pipeline:
    filter_normal: false
    pipeline_connection: zeromq

  logsight_jobs:
    incident_job:
      interval: 60
      n_jobs: 2
    es_cleanup_job:
      interval: 3600
      cleanup_age: now-1y
  retryAttempts: 5
  retryTimeout : 10
  connections:
    postgres:
      host: postgresql
      port: 5432
      db: logsight
      username: logsight
    elasticsearch:
      scheme: http
      host: elasticsearch-master
      port: 9200
      username: elastic
    zeromq:
      host: logsight-backend
      port: 5559
    kibana:
      hostname: logsight-kibana
      port: 5601
    kafka:
      host: kafka
      port: 9092
      topic: pipeline

## Configuration values for postgresql dependency
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md
postgresql:
  # Enable to deploy the bitnami PostgreSQL chart
  enabled: true

  nameOverride: "postgresql"
  fullnameOverride: "postgresql"

  persistence:
    enabled: true
    size: 2Gi
  image:
    tag: 11

kafka:
  enabled: true
  nameOverride: "kafka"
  fullnameOverride: "kafka"
  maxMessageBytes: _5242880
  zookeeper:
    enabled: true

global:
  postgresql:
    auth:
      username: logsight
      password: logsight
      database: logsight
    service:
      port: 5432




elasticsearch:

  enabled: true
  # we only use a single-node cluster for our deployment
  singleNode: true
  # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx512m -Xms512m"

  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: true
      xpack.security.transport.ssl.enabled: true
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
      xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12

  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: username

  secretMounts:
    - name: elastic-certificates
      secretName: elastic-certificates
      path: /usr/share/elasticsearch/config/certs

  replicas: 1
  clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'


  # Allocate smaller chunks of memory per pod.
  # resources:
  #   requests:
  #     cpu: "100m"
  #     memory: "1G"
  #   limits:
  #     cpu: "1000m"
  #     memory: "1G"

  # Request smaller persistent volumes.
  # volumeClaimTemplate:
  #   accessModes: [ "ReadWriteOnce" ]
  #   storageClassName: "standard"
  #   resources:
  #     requests:
  #       storage: 8G

kibana:
  enable: true
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: username
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: password
    - name: 'KIBANA_ENCRYPTION_KEY'
      valueFrom:
        secretKeyRef:
          name: kibana
          key: encryptionkey

  # kibanaConfig:
  #   kibana.yml: |
  #     server.ssl:
  #       enabled: true
  #       key: /usr/share/kibana/config/certs/elastic-certificate.pem
  #       certificate: /usr/share/kibana/config/certs/elastic-certificate.pem
  #     xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
  #     elasticsearch.ssl:
  #       certificateAuthorities: /usr/share/kibana/config/certs/elastic-certificate.pem
  #       verificationMode: certificate

  secretMounts:
    - name: elastic-certificate-pem
      secretName: elastic-certificate-pem
      path: /usr/share/kibana/config/certs