apiVersion: v1
kind: Service
metadata:
  name: {{ include "logsight.fullname" . }}
  labels:
    {{- include "logsight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: log-stream
  selector:
    {{- include "logsight.selectorLabels" . | nindent 4 }}
